package com.example.stock_control.constants

enum class CardType {
    PRODUCT_UPDATE,PRODUCT_DELETE,
    SUPPLIER_UPDATE,SUPPLIER_DELETE,
    STOCK_UPDATE,STOCK_DELETE,
    PRODUCT_SEARCH,SUPPLIER_SEARCH, STOCK_SEARCH,
    STOCK_REPLENISHMENT_LIST, STOCK_TOTAL,SALE_TOTAL
}